### ISSUE TITLE
Beautylog causing issues with gulp-typings

### ISSUE THREAD

**Issue by napalm684** [typings/gulp-typings#14]
We had no problems until today when we reinstalled our NPM modules fresh.  I uninstalled and reinstalled the gulp-typings and beautylog packages to no avail.  Here is the error detail.

Failed to run "C:\xxxx\Gulpfile.js"...
cmd.exe /c gulp --tasks-simple
C:xxxx\node_modules\beautylog\dist\beautylog.classes.table.js:3
const plugins = require("./beautylog.plugins");
^^^^^
SyntaxError: Use of const in strict mode.
    at Module._compile (module.js:439:25)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)
    at Object.<anonymous> (C:\xxxx\node_modules\beautylog\dist\index.js:4:33)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)

**Comment by philkunz** [comment]
Hi, this is due to me changing the complete stack to es6 since node 6 is becoming LTS in the near future. Use https://babeljs.io/docs/usage/require/ to use es6 code if you require an older node version for some reason. Or submit an PR that gets rid of beautylog in gulp-typings. Or check out the new @types npm scope to manage typings with TypeScript 2.0

**Comment by napalm684** [comment]
I kinda think this is unreasonable.  You are asking typescript devs to use another transpiler to transpile the transpiled output again?  It'd be one thing if node 6 was ready but it's not.

**Comment by dangler** [comment]
I agree with @napalm684 on this. It seems a bit unreasonable to ask to move to babel. Since the developer of beautylogs change this up, can the dependency be locked at the previous version?

**Comment by dangler** [comment]
Shouldn't this change been a minor version changes instead of a patch version change?

**Comment by philkunz** [comment]
I just pushed a PR that removes beautylog as dependency. Someone from the typings team needs to merge it and push it to npm since they took over from me on gulp-typings.

Sorry for the confusion.

**Comment by dangler** [comment]
Thank you

**Comment by napalm684** [comment]
Indeed thank you!

**Comment by dangler** [comment]
Looks like you closed the PR?

**Comment by philkunz** [comment]
should be fixed. Removed all ES6 dependencies. Please report back in case any problems persist.

**Comment by philkunz** [comment]
Check version 2.0.1 on npm.

**Comment by napalm684** [comment]
Hi @philkunz I tested this out this morning and seem to be having the same issue but with a different require:

```
Failed to run "C:\xxxx\Gulpfile.js"...
cmd.exe /c gulp --tasks-simple
C:\xxxx\node_modules\gulp-typings\dist\index.js:3
const plugins = require("./gulp-typings.plugins");
^^^^^
SyntaxError: Use of const in strict mode.
    at Module._compile (module.js:439:25)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)
    at Object.<anonymous> (C:\xxxx\gulpfile.js:15:19)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
```
